CREATE TABLE IF NOT EXISTS ITEM(

    itemID INTEGER NOT NULL PRIMARY KEY

);

CREATE TABLE IF NOT EXISTS SELLER(
    sellerID INTEGER NOT NULL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS SUPPLIER(
    supplierID INTEGER NOT NULL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS CUSTOMER(
    customerID INTEGER NOT NULL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS INVOICEQUOTE(
    invoiceQuoteID INTEGER NOT NULL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS REPORT(
    reportID INTEGER NOT NULL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS STAFF(
    staffID INTEGER NOT NULL PRIMARY KEY
);