-- CREATE TABLE ITEM(

--     itemID INTEGER NOT NULL PRIMARY KEY

-- );

-- CREATE TABLE SELLER(
--     sellerID INTEGER NOT NULL PRIMARY KEY
-- );

-- CREATE TABLE SUPPLIER(
--     supplierID INTEGER NOT NULL PRIMARY KEY
-- );

-- CREATE TABLE CUSTOMER(
--     customerID INTEGER NOT NULL PRIMARY KEY
-- );

-- CREATE TABLE INVOICEQUOTE(
--     invoiceQuoteID INTEGER NOT NULL PRIMARY KEY
-- );

-- CREATE TABLE REPORT(
--     reportID INTEGER NOT NULL PRIMARY KEY
-- );

-- CREATE TABLE STAFF(
--     staffID INTEGER NOT NULL PRIMARY KEY
-- );